### ISSUE TITLE
Incomplete SW group operations may be worthwhile

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/r1cs-std#14]
This is to be left as a todo for the future. 

There seems to be a big gap in constraints & density of complete vs incomplete group operations, as well as operations on affine vs projective.

Ideally, if permitted by completeness and soundness, incomplete + affine can lead to fewer constraints & lower density. 

However, it seems to require certain efforts to investigate whether the soundness holds, and to what extent. And completeness would be a separate issue that the application needs to handle. Especially, the application needs to have some sort of "reject sampling" so that it can retry proving until it avoids the incompleteness barriers.

**Comment by weikengchen** [comment]
A potential fix for completeness during additions is probably this:

- Assume we are adding multiple points.
- The prover can instantiate any non-infinity point as the initial value. The prover is supposed to choose a random one.
- The prover needs to subtract the same point as the end.

Since the initial value is random, it may be able to provide some sort of "reject sampling".

**Comment by Pratyush** [comment]
This issue shows that maybe one can do this without exceptions inside the circuit: https://github.com/zcash/zcash/issues/3924

So the idea would be to convert to affine form, check for exceptional cases in the scalar,  perform scalar multiplications via the foregoing algorithm, and to then convert back to projective form.

**Comment by Pratyush** [comment]
In particular these portions seem relevant: *

* Double and add: https://github.com/ebfull/halo/blob/d9d341f19b1122f975c2fc7c583490a830a9020a/src/gadgets/ecc.rs#L1327
* Scalar multiply: https://github.com/ebfull/halo/blob/d9d341f19b1122f975c2fc7c583490a830a9020a/src/gadgets/ecc.rs#L1490

**Comment by weikengchen** [comment]
For the record, based on a measurement, our current implementation has roughly 12 constraints and 71 non-zeros per addition.

**Comment by weikengchen** [comment]
The solution with exceptions may have 11 constraints, as follows:

- Convert each of the two points to their affine forms => getting x/z and y/z, 2 * 2 = 4 constraints. This check also rules out the infinity points.
- Check the exceptional case; so, it requires that x1 does not equal x2, 1 constraint
- The foregoing algorithm, 6 constraints 

So the saving is not significant.

**Comment by weikengchen** [comment]
If the projective form is unused, but we only use the affine form, then maybe we can have fewer constraints, I assume:

- Check x1 does not equal x2 requires 1 constraint => this is because the addition formula will fail for doubling.
- The foregoing algorithm, 6 constraints.

Given that the affine form is likely to behave very differently from the complete form, it seems better to have a separate trait for it (so, not CurveVar). Any idea on the traits and implementations?

**Comment by Pratyush** [comment]
> The solution ~with~ without exceptions may have 11 constraints, as follows:
> 
>     * Convert each of the two points to their affine forms => getting x/z and y/z, 2 * 2 = 4 constraints. This check also rules out the infinity points.
> 
>     * Check the exceptional case; so, it requires that x1 does not equal x2, 1 constraint
> 
>     * The foregoing algorithm, 6 constraints
> 
> 
> So the saving is not significant.

I think the idea would be to use the exceptional-addition inside scalar multiplication, where it seems we can do an edge-case once check at the beginning.

**Comment by Pratyush** [comment]
By the way, another option for some curves with a cofactor is to convert to an alternate form (eg: edwards), and to perform the scalar arithmetic there, and to then convert back to short weierstrass form.

**Comment by zhenfeizhang** [comment]
> In particular these portions seem relevant: *
> 
> * Double and add: https://github.com/ebfull/halo/blob/d9d341f19b1122f975c2fc7c583490a830a9020a/src/gadgets/ecc.rs#L1327
> * Scalar multiply: https://github.com/ebfull/halo/blob/d9d341f19b1122f975c2fc7c583490a830a9020a/src/gadgets/ecc.rs#L1762

Is there an API to call scalar multiplications over an EdwardsVar as in the second link? 
Or are the callers expected to do a double-then-add approaches?

**Comment by weikengchen** [comment]
@zhenfeizhang The current library implements group elements on Edward curves as `ProjectiveCurve` and `AffineCurve`, so they can use the corresponding interfaces: https://github.com/arkworks-rs/algebra/blob/master/ec/src/models/twisted_edwards_extended.rs

And the `ProjectiveCurve` interface has `mul`: https://github.com/arkworks-rs/algebra/blob/master/ec/src/lib.rs#L209, which can be used for scalar mult.

**Comment by Pratyush** [comment]
see also [this paper](https://sci-hub.se/https://link.springer.com/chapter/10.1007/978-3-319-22425-1_4) which reduces the number of muls compared to [[ELM02]](https://arxiv.org/abs/math/0208038).

**Comment by zhenfeizhang** [comment]
I guess there was some misunderstanding. I am wondering about group muls over `Var`s rather than `ProjectiveCurve` or `AffineCurve`. Is there an API for this? Or should the caller to it themselfs?  

looking at the code here:
https://github.com/arkworks-rs/crypto-primitives/blob/ce5cc89011b394eb006987a24088947d5099d641/src/commitment/pedersen/constraints.rs#L77

it seems that there isn't an API -- the caller needs to decomposite the scalars and then do the scalar mul.
Is this a fair understanding?

**Comment by weikengchen** [comment]
@zhenfeizhang I look up the curve's interface, does this one work for you? https://github.com/arkworks-rs/succinct_r1cs/blob/0164f52ae0109c6e0a89c75fc9abc66c4ec0c5dc/r1cs-std/src/groups/mod.rs#L91

**Comment by zhenfeizhang** [comment]
LOL. This is likely a private repo :-) I don't have access

**Comment by weikengchen** [comment]
Sorry, wrong link. This one: https://github.com/arkworks-rs/r1cs-std/blob/636f93a3e5fea8f2165f725f2edded544159a978/src/groups/mod.rs#L91

**Comment by zhenfeizhang** [comment]
Yes. Thanks!

**Comment by Pratyush** [comment]
So, this is implemented now, but without the optimizations from https://github.com/zcash/zcash/issues/3924
