### ISSUE TITLE
How to cmp two FqVar

### ISSUE THREAD

**Issue by brucechin** [arkworks-rs/r1cs-std#32]
Hello, suppose I have two FqVar 

```
  let tmp1 =      FpVar::<Fq>::new_witness(r1cs_core::ns!(cs, format!("tmp1")), || Ok(a),).unwrap();
  let tmp2 =      FpVar::<Fq>::new_witness(r1cs_core::ns!(cs, format!("tmp2")), || Ok(b),).unwrap();
```

I want to cmp them using `cmp` trait. The following code gets error:

`tmp1.cmp(&tmp2);`

> the method `cmp` exists but the following trait bounds were not satisfied:
>             `r1cs_std::fields::fp::FpVar<algebra_core::Fp256<algebra::bls12_381::FrParameters>>: std::iter::Iterator`
>             which is required by `&mut r1cs_std::fields::fp::FpVar<algebra_core::Fp256<algebra::bls12_381::FrParameters>>: std::iter::Iterator`

How can I compare two FqVar like I compare two integers?

I can only find `enforce_cmp`, but obviously, it is not what I want.

**Comment by weikengchen** [comment]
You can have a try on `is_cmp`: https://github.com/arkworks-rs/r1cs-std/blob/master/src/fields/fp/cmp.rs#L45
This one can be used for ">= or <" or "<= or >".

If you want three outcomes "< = >", you likely need to combine with `is_eq`.

**Comment by brucechin** [comment]
Thanks for your reply. I tried is_cmp() function but somehow the return value is neither Ok(Boolean::Constant(true)) nor Ok(Boolean::Constant(false)). because I did not find a testcase for this function, I have not figured out how to deal with its output...

```
match tmp1.is_cmp(&tmp2, Ordering::Greater, false){
  Ok(Boolean::Constant(true)) => {do something1}
  Ok(Boolean::Constant(false)) => {do something2}
  _ => {do something3}
}
```

in this example, the code always executes do something3

**Comment by Pratyush** [comment]
If the field elements being compared are not constants, then the outputs of comparison will not be constants either.

**Comment by brucechin** [comment]
Then how could i know if the output is true or false? i can not use the trait `r1cs_std::select::CondSelectGadget<algebra_core::Fp256<algebra::bls12_381::FrParameters>>' too like:

```
let cmp_res = tmp1.is_cmp(&tmp2, Ordering::Greater, false);
let the_larger_one = cmp_res.select(&tmp1, &tmp2).unwrap();
```

**Comment by weikengchen** [comment]
I think the reason why the code above fails is that:

`is_cmp`'s output is `Result<Boolean<_>, _>`, so you need to unwrap it first.

**Comment by brucechin** [comment]
I have Ok(). I can check 

`cmp.value()? == true`

But I am afraid that this is not secure and leak the value of `cmp`

**Comment by weikengchen** [comment]
You can do that for sure. Just you need to make sure that the relationship that you desired is enforced in the constraint system.

**Comment by weikengchen** [comment]
And by the way, when I mentioned

```
I think the reason why the code above fails is that:

is_cmp's output is Result<Boolean<_>, _>, so you need to unwrap it first.
```

I am referring to `let cmp_res = tmp1.is_cmp(&tmp2, Ordering::Greater, false);`

**Comment by brucechin** [comment]
I see. Then i will use the `cmp.value()? == true` way to implement my logic. Thanks for your help again!

**Comment by weikengchen** [comment]
And also, `value()?` would fail during the circuit setup. This is because, during the circuit setup, assignments are ignored, so `value()?` would say "assignment missing".

There are two ways:
- Replace `value()?` with `value().unwrap_or_default()` and be prepared that during the circuit setup, all the value assignments could be false or some other random values.
- Put `value()?` only in the closure of `new_variable`'s second argument (a function to provide the new variable's assignment), which would be ignored during the setup but executed in the non-setup mode.

**Comment by brucechin** [comment]
Yeah. I met assignment missing error before when I use something like assert_eq!(tmp1.to_bits_le().values(), tmp2.to_bits_le().values()) for debugging purposes.

**Comment by Pratyush** [comment]
So in general you don't want to ever inspect the values assigned to variables during constraint generation; the values can differ across invocations (for example, when the witness differs)

Rather, if you want to perform selection, here's a code snippet that should work:
```rust
let cmp_res = tmp1.is_cmp(&tmp2, Ordering::Greater, false)?;
let the_larger_one = cmp_res.select(&tmp1, &tmp2).unwrap();
```
(Note the `?` at the end of the first line.)

**Comment by brucechin** [comment]
Indeed. Using select is a much elegant way to achieve the same goal. Thanks for this code snippet!
