### ISSUE TITLE
cargo test results in errors

### ISSUE THREAD

**Issue by hadasz** [arkworks-rs/r1cs-std#37]
Hi, when I run `cargo test`, I get the following errors:
-  the trait bound `[bits::boolean::Boolean<F>; 16]: std::convert::From<std::vec::Vec<_>>` is not satisfied
- the trait bound `[bits::boolean::Boolean<F>; 32]: std::convert::From<std::vec::Vec<_>>` is not satisfied
-  the trait bound `&[bits::boolean::Boolean<F>; 64]: std::iter::IntoIterator` is not satisfied .. etc
All the issues seem to be around the  Boolean type.
Thanks

**Comment by weikengchen** [comment]
Can you provide your Rust compiler version? A number of the implementations in the code only work in the latest stable

**Comment by hadasz** [comment]
when I do `cargo rustc -- --version` I get  "rustc 1.46.0"
I did `rustup install stable` before building as well

**Comment by weikengchen** [comment]
Let me have a try.

**Comment by weikengchen** [comment]
I updated my Rust to the latest version. `rustup show` shows the following:

```
Default host: x86_64-apple-darwin
rustup home:  /Users/cusgadmin/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
beta-x86_64-apple-darwin
nightly-2020-04-20-x86_64-apple-darwin
nightly-2020-05-15-x86_64-apple-darwin
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-unknown-none
thumbv6m-none-eabi
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

Two things that you can try:

1. `cargo update` on this repo, in case there are some upstream repos being updated but the local copy is not synced.
2. check `rustup default` to see if the default compiler is beta or nightly.

**Comment by hadasz** [comment]
Thank you for looking into this. It's still giving me the same errors but it seems like it might be an issue with my toolchain, so I will investigate that.

**Comment by hadasz** [comment]
I have confirmed that the oroblem was that I had an old dependency in my ~/.cargo/bin . Thanks again for the help

**Comment by weikengchen** [comment]
We recently encountered this issue. This might have something to do with whether or not `~/.cargo/env` is loaded (in .zshrc or .bashrc, of your shells). This file is supported to overwrite the system's Rust and use the user's Rust in the $PATH.

**Comment by hadasz** [comment]
Just to close this out - the issue was that I had rustup installed from homebrew, AND from the official source. cargo was defaulting to the homebrew version. Thanks again for your help, it's running now.
