### ISSUE TITLE
Add `Radix2Domain` where offset is not constant

### ISSUE THREAD

**Issue by tsunrise** [arkworks-rs/r1cs-std#64]
## Summary

There are cases where we need a coset domain where offset is not a constant (for example, the query coset in FRI). It is probably better to add this to `r1cs-std`. 

## Proposal

~~Add a struct called `QueriedRadix2Domain` (is there a better name?). Methods are similar to `Radix2Domain`.~~
Make `Radix2Domain` have offset that is not constant. Specialize when `offset` is constant or variable. 

Some codes to copy from (ignore it if you do not have access to the link. Repo is currently private):
- struct definition: https://github.com/alexchmit/perfect-constraints/blob/79692f2652a95a57f2c7187f5b5276345e680230/fractal/src/ldt/mod.rs#L11-L20
- interpolation (we can replace `alpha` with `point`): https://github.com/alexchmit/perfect-constraints/blob/79692f2652a95a57f2c7187f5b5276345e680230/fractal/src/ldt/fri/single_round_fri.rs#L38-L69

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by weikengchen** [comment]
(For interested readers who may come across this topic, the alexchmit/perfect-constraints is currently a private repo)

**Comment by ValarDragon** [comment]
Shouldn't it be fine to make the Radix2Domain in r1cs-std have an offset parameter that is an `FpVar`. Then it can specialize relevant methods if its FpVar::Constant or FpVar::Var?

**Comment by tsunrise** [comment]
> Shouldn't it be fine to make the Radix2Domain in r1cs-std have an offset parameter that is an `FpVar`. Then it can specialize relevant methods if its FpVar::Constant or FpVar::Var?

That makes sense. We should do this instead.
