### ISSUE TITLE
Implement the `Sum` trait for `FpVar`

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/r1cs-std#68]
## Summary

This is related to Lianke's post (https://github.com/arkworks-rs/groth16/issues/33). Since he is working on ZKP for neural networks (see: https://eprint.iacr.org/2021/087). I feel that maybe one of the implementations for FpVar has caused the LC map to blow up.

@brucechin

## Problem Definition

Consider that we are adding many numbers together. At this moment, when we add two numbers, we create, not a constraint, but a new LC.

If we know that we are adding many numbers together, then we may want to create one LC for the sum, not N - 1 new LCs.

This is just to cut down the depth of the inlining.

## Proposal

Implement the `Sum` trait for `FpVar` (which implies that we need to implement for `AllocatedFp` as well).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by brucechin** [comment]
Yeah, it is intuitive that reducing the inlining depth can help.
