### ISSUE TITLE
Handling zero as base in group scalar multiplication

### ISSUE THREAD

**Issue by deevashwer** [arkworks-rs/r1cs-std#94]
## Summary of Bug

Group scalar multiplication with `ark-pallas` is leading to the failure of inverse constraint when the group element is 0.  
I also tried `ark-mnt4-298` and did not observe any issues; I haven't tried other curves.

## Version

`ark-pallas = { version = "^0.3.0", features = ["curve", "r1cs"], default-features = false  }`

## Steps to Reproduce

The following function reproduces the error.

```
    pub fn scalar_mul_bug() {
        let scalar: <G as AffineCurve>::ScalarField = BigInteger256::new([13446945587828132253, 13946564884975567571, 1632334266307653820, 1541582214770829428]).into();
        let base = G::zero();
        let cs = ConstraintSystem::<CF>::new_ref();
        let scalar_var = NonNativeFieldVar::new_input(cs.clone(), || Ok(scalar)).unwrap();
        println!("scalar_var: {:?}", scalar_var.value());
        let scalar_var_le = scalar_var.to_bits_le().unwrap();
        println!("scalar_var_le: {:?}", scalar_var_le.value());
        let base_var = C::new_input(cs.clone(), || Ok(base)).unwrap();
        println!("base_var: {:?}", base_var.value().unwrap().into_affine());
        let res = base_var.scalar_mul_le(scalar_var_le.iter()).unwrap();
        println!("res: {:?}", res.value().unwrap().into_affine());
        res.enforce_equal(&base_var).unwrap();
        assert!(cs.is_satisfied().unwrap());
    }
```

**Comment by jules** [comment]
Ran into this as well, constraints aren't satisfied when attempting to do a scalar mul in circuit for a zero base.

**Comment by burdges** [comment]
Isn't this expected behavior for short weierstrass curves?  It's kinda why Edwards curves exists, ala https://safecurves.cr.yp.to/complete.html
